steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/groovybits/gaib:$COMMIT_SHA', '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}', '.']
images: ['gcr.io/$PROJECT_ID/github.com/groovybits/gaib:$COMMIT_SHA']

