steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/github.com/groovybits/gaib:$COMMIT_SHA'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
  - '--build-arg'
  - 'OPENAI_API_KEY=${_OPENAI_API_KEY}'
  - '--build-arg'
  - 'PINECONE_API_KEY=${_PINECONE_API_KEY}'
  - '--build-arg'
  - 'PINECONE_ENVIRONMENT=${_PINECONE_ENVIRONMENT}'
  - '--build-arg'
  - 'PINECONE_INDEX_NAME=${_PINECONE_INDEX_NAME}'
  - '--build-arg'
  - 'PINECONE_NAME_SPACE=${_PINECONE_NAME_SPACE}'
  - '--build-arg'
  - 'OTHER_PINECONE_NAMESPACES=${_OTHER_PINECONE_NAMESPACES}'
  - '--build-arg'
  - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
  - '--build-arg'
  - 'GOOGLE_APPLICATION_CREDENTIALS_JSON=${_GOOGLE_APPLICATION_CREDENTIALS_JSON}'
  - '--build-arg'
  - 'GOOGLE_TRANSLATE_API_KEY=${_GOOGLE_TRANSLATE_API_KEY}'
  - '--build-arg'
  - 'PEXELS_API_KEY=${_PEXELS_API_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FIREBASE_REGION=${_NEXT_PUBLIC_FIREBASE_REGION}'
  - '--build-arg'
  - 'NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${_NEXT_PUBLIC_STRIPE_PUBLIC_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_STRIPE_PRICE_ID=${_NEXT_PUBLIC_STRIPE_PRICE_ID}'
  - '--build-arg'
  - 'STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY}'
  - '--build-arg'
  - 'NEXT_PUBLIC_PREMIUM_TOKEN_BALANCE=${_NEXT_PUBLIC_PREMIUM_TOKEN_BALANCE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FREE_TOKEN_START=${_NEXT_PUBLIC_FREE_TOKEN_START}'
  - '--build-arg'
  - 'HOST=${_HOST}'
  - '--build-arg'
  - 'NEXT_PUBLIC_GAIB_IMAGE_DIRECTORY_URL=${_NEXT_PUBLIC_GAIB_IMAGE_DIRECTORY_URL}'
  - '--build-arg'
  - 'NEXT_PUBLIC_GAIB_IMAGE_MAX_NUMBER=${_NEXT_PUBLIC_GAIB_IMAGE_MAX_NUMBER}'
  - '--build-arg'
  - 'NEXT_PUBLIC_GAIB_DEFAULT_IMAGE=${_NEXT_PUBLIC_GAIB_DEFAULT_IMAGE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_BASE_URL=${_NEXT_PUBLIC_BASE_URL}'
  - '--build-arg'
  - 'GPT_MAX_TOKENS=${_GPT_MAX_TOKENS}'
  - '--build-arg'
  - 'NEXT_PUBLIC_GCS_BUCKET_NAME=${_NEXT_PUBLIC_GCS_BUCKET_NAME}'
  - '--build-arg'
  - 'NEXT_PUBLIC_LOGIN_AUTH_ENABLE=${_NEXT_PUBLIC_LOGIN_AUTH_ENABLE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_IMAGE_SAVING=${_NEXT_PUBLIC_ENABLE_IMAGE_SAVING}'
  - '--build-arg'
  - 'NEXT_PUBLIC_IMAGE_GENERATION_EXAMPLES=${_NEXT_PUBLIC_IMAGE_GENERATION_EXAMPLES}'
  - '--build-arg'
  - 'NEXT_PUBLIC_IMAGE_GENERATION_PROMPTS=${_NEXT_PUBLIC_IMAGE_GENERATION_PROMPTS}'
  - '--build-arg'
  - 'NEXT_PUBLIC_FEED_PAGE_SIZE=${_NEXT_PUBLIC_FEED_PAGE_SIZE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_IMAGE_SERVICE=${_NEXT_PUBLIC_IMAGE_SERVICE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_SPEAKING=${_NEXT_PUBLIC_ENABLE_SPEAKING}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_IMAGES=${_NEXT_PUBLIC_ENABLE_IMAGES}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_TRANSLATE=${_NEXT_PUBLIC_ENABLE_TRANSLATE}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_NEWS_FEED=${_NEXT_PUBLIC_ENABLE_NEWS_FEED}'
  - '--build-arg'
  - 'NEXT_PUBLIC_ENABLE_AUTH=${_NEXT_PUBLIC_ENABLE_AUTH}'
  - '.'
images: ['gcr.io/$PROJECT_ID/github.com/groovybits/gaib:$COMMIT_SHA']
