export interface Language {
    code: string;
    name: string;
  }
  
  export const audioLanguages: Language[] = [
    { code: "ja-JP", name: "Japanese (ja-JP)" },
    { code: "en-US", name: "English (en-US)" },
    { code: "en-GB", name: "English Great Britain (en-GB)" },
    { code: "zh-CN", name: "Chinese (zh-CN)" },
    { code: "es-ES", name: "Spanish (es-ES)" },
    { code: "fr-FR", name: "French (fr-FR)" },
    { code: "it-IT", name: "Italian (it-IT)" },
    { code: "de-DE", name: "German (de-DE)" },
    { code: "pt-BR", name: "Portuguese Brazil (pt-BR)" },
    { code: "pt-PT", name: "Portuguese (pt-PT)" },
    { code: "ru-RU", name: "Russian (ru-RU)" },
    { code: "ko-KR", name: "Korean (ko-KR)" },
    { code: "ar-SA", name: "Arabic (ar-SA)" },
    { code: "hi-IN", name: "Hindi (hi-IN)" },
    { code: "nl-NL", name: "Dutch (nl-NL)" },
    { code: "pl-PL", name: "Polish (pl-PL)" },
    { code: "tr-TR", name: "Turkish (tr-TR)" },
    { code: "sv-SE", name: "Swedish (sv-SE)" },
    { code: "da-DK", name: "Danish (da-DK)" },
    { code: "nb-NO", name: "Norwegian (nb-NO)" },
    { code: "fi-FI", name: "Finnish (fi-FI)" },
    { code: "cs-CZ", name: "Czech (cs-CZ)" },
    { code: "el-GR", name: "Greek (el-GR)" },
    { code: "hu-HU", name: "Hungarian (hu-HU)" },
    { code: "ro-RO", name: "Romanian (ro-RO)" },
    { code: "sk-SK", name: "Slovak (sk-SK)" },
    { code: "th-TH", name: "Thai (th-TH)" },
    { code: "vi-VN", name: "Vietnamese (vi-VN)" },
    { code: "id-ID", name: "Indonesian (id-ID)" },
    { code: "ms-MY", name: "Malay (ms-MY)" },
    { code: "fil-PH", name: "Filipino (fil-PH)" },
    { code: "uk-UA", name: "Ukrainian (uk-UA)" },
    { code: "he-IL", name: "Hebrew (he-IL)" },
    /*{ code: "bo", name: "Tibetan (bo)" },*/
    { code: "sa", name: "Sanskrit (sa)" },
  ];
  
  export const subtitleLanguages: Language[] = [
    { code: "en-US", name: "English (en-US)" },
    { code: "ja-JP", name: "Japanese (ja-JP)" },
    { code: "en-GB", name: "English Great Britain (en-GB)" },
    { code: "zh-CN", name: "Chinese (zh-CN)" },
    { code: "es-ES", name: "Spanish (es-ES)" },
    { code: "fr-FR", name: "French (fr-FR)" },
    { code: "it-IT", name: "Italian (it-IT)" },
    { code: "de-DE", name: "German (de-DE)" },
    { code: "pt-BR", name: "Portuguese Brazil (pt-BR)" },
    { code: "pt-PT", name: "Portuguese (pt-PT)" },
    { code: "ru-RU", name: "Russian (ru-RU)" },
    { code: "ko-KR", name: "Korean (ko-KR)" },
    { code: "ar-SA", name: "Arabic (ar-SA)" },
    { code: "hi-IN", name: "Hindi (hi-IN)" },
    { code: "nl-NL", name: "Dutch (nl-NL)" },
    { code: "pl-PL", name: "Polish (pl-PL)" },
    { code: "tr-TR", name: "Turkish (tr-TR)" },
    { code: "sv-SE", name: "Swedish (sv-SE)" },
    { code: "da-DK", name: "Danish (da-DK)" },
    { code: "nb-NO", name: "Norwegian (nb-NO)" },
    { code: "fi-FI", name: "Finnish (fi-FI)" },
    { code: "cs-CZ", name: "Czech (cs-CZ)" },
    { code: "el-GR", name: "Greek (el-GR)" },
    { code: "hu-HU", name: "Hungarian (hu-HU)" },
    { code: "ro-RO", name: "Romanian (ro-RO)" },
    { code: "sk-SK", name: "Slovak (sk-SK)" },
    { code: "th-TH", name: "Thai (th-TH)" },
    { code: "vi-VN", name: "Vietnamese (vi-VN)" },
    { code: "id-ID", name: "Indonesian (id-ID)" },
    { code: "ms-MY", name: "Malay (ms-MY)" },
    { code: "fil-PH", name: "Filipino (fil-PH)" },
    { code: "uk-UA", name: "Ukrainian (uk-UA)" },
    { code: "he-IL", name: "Hebrew (he-IL)" },  
    /*{ code: "bo", name: "Tibetan (bo)" },*/ // Google has this in research, not public yet
    { code: "sa", name: "Sanskrit (sa)" },
];
  